# docker-compose.yml
version: '3.8'

services:
  collector:
    build:
      context: .
      dockerfile: Dockerfile.collector
    volumes:
      - ./data:/app/data
    restart: unless-stopped

  dashboard:
    build:
      context: .
      dockerfile: Dockerfile.dashboard
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
